### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ferdi05**
Replace the old logo with a new one

# Pull Request

## What does this PR do?
Fixes #<issue_number>

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to MeiliSearch!

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
I validate that and press the green button!

**Comment by driesvints** [comment]
@ferdi05 @Kerollmops Hi there. It seems this logo is very close resembling the Eventy one: https://twitter.com/eventyio

I'd like to start an open conversation with you to find out how the design process went with your new logo. Given the fact that we hired someone to design ours we want to make sure that no IP of ours was just copied over.

**Comment by qdequele** [comment]
Hello @driesvints, We've used an agency to work on our branding. They are called [unfold](https://unfold.co/) and you can watch their [Dribbble](https://dribbble.com/unfold/shots). It was a very long process that we did 2 times before having this new branding. And they involved 5 designers in the process. If you want to talk about it or if you need proof or anything. You can contact me at quentin@meilisearch.com.

**Comment by driesvints** [comment]
Hey @qdequele, thank you. I'll reach out 👍

**Pull request merged**
