### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CaroFG**
Update company and integrations info

### CODE REVIEW

**Comment by ferdi05** [comment]
@CaroFG Is this text from the new website?

**Comment by CaroFG** [comment]
It's from Meilisearch repo's README that we reworked a while ago, I made the changes here to be consistent, plus it was validated by all the teams including the docs team

**Review by ferdi05 — APPROVED** [review]
All good!

**Comment by ferdi05** [comment]
> It's from Meilisearch repo's README that we reworked a while ago, I made the changes here to be consistent, plus it was validated by all the teams including the docs team

Then you didn't really need my review, you could have merged it yourself :) Anyway, thanks for this!

**Pull request merged**
